apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-metrics.fullname" . }}
  labels:
    app.kubernetes.io/name: backend-metrics
    app.kubernetes.io/instance: backend-metrics
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: backend-metrics
    app.kubernetes.io/instance: backend-metrics

